"use client";

import { useEffect, useState } from "react";
import { MapPin, Plus, Warehouse } from "lucide-react";
import { adminApi } from "@/lib/api";

export function WarehouseManager() {
  const [warehouses, setWarehouses] = useState([]); const [name, setName] = useState(""); const [code, setCode] = useState(""); const [address, setAddress] = useState(""); const [message, setMessage] = useState("");
  const load = async () => { try { const result = await adminApi.warehouses.list(); setWarehouses(result.data || []); } catch (error) { setMessage(error.message || "Could not load warehouses."); } };
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  const create = async (event) => { event.preventDefault(); try { await adminApi.warehouses.create({ name, code: code.toUpperCase(), address: address || undefined }); setName(""); setCode(""); setAddress(""); setMessage("Warehouse added."); void load(); } catch (error) { setMessage(error.message || "Could not create warehouse."); } };
  return <div className="warehouse-manager"><header className="admin-page-heading"><div><p className="admin-eyebrow">Inventory locations</p><h1>Warehouses</h1><p>See how much product is available in each warehouse.</p></div></header>{message && <p className="product-builder-message">{message}</p>}<section className="warehouse-create-card"><div><Warehouse /><h2>Add warehouse</h2><p>Create a stock location before assigning quantities to a product.</p></div><form onSubmit={create}><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Warehouse name" required /><input value={code} onChange={(e) => setCode(e.target.value.toUpperCase())} placeholder="Code, e.g. BLR-01" required /><input value={address} onChange={(e) => setAddress(e.target.value)} placeholder="Address (optional)" /><button className="admin-primary-button"><Plus /> Add warehouse</button></form></section><section className="warehouse-grid">{warehouses.map((warehouse) => { const total = warehouse.stocks?.reduce((sum, stock) => sum + stock.quantity, 0) || 0; return <article key={warehouse.id} className="warehouse-card"><header><div><i><Warehouse /></i><div><h2>{warehouse.name}</h2><span>{warehouse.code}</span></div></div><strong>{total} units</strong></header>{warehouse.address && <p><MapPin /> {warehouse.address}</p>}<div className="warehouse-stock-list">{warehouse.stocks?.length ? warehouse.stocks.map((stock) => <div key={stock.id}><span>{stock.variant.product.title} · {stock.variant.option1 || stock.variant.title}</span><b>{stock.quantity}</b></div>) : <span>No stock assigned yet.</span>}</div></article>; })}{!warehouses.length && <div className="product-catalog-empty"><Warehouse /><h2>No warehouses yet</h2><p>Add your first location to start tracking quantities.</p></div>}</section></div>;
}
